### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by dpapperini** [ckhandla94/backpack-import#2]
When I try to publish vendor with this command:

`php artisan vendor:publish --provider="BackpackImport\BackpackImportServiceProvider"`

return this error: Unable to locate publishable resources.

**Comment by WRedMedia** [comment]
Same here, any suggestions ?

**Comment by ckhandla94** [comment]
> Same here, any suggestions ?

Sorry for delay, Give me some time I will fix it today.

**Comment by ckhandla94** [comment]
> Same here, any suggestions ?

I have just tried in latest version of backpack and larval, I have no error. If possible please describe error or send me screen shorts and versions of Backpack and Laravel

**Comment by WRedMedia** [comment]
> > Same here, any suggestions ?
> 
> I have just tried in latest version of backpack and larval, I have no error. If possible please describe error or send me screen shorts and versions of Backpack and Laravel

![image](https://user-images.githubusercontent.com/8059351/146371487-8443fa06-a02b-418f-9c21-753895d43d5c.png)
![image](https://user-images.githubusercontent.com/8059351/146371553-558553f2-bafb-4df8-b9b5-58332d04698e.png)

Laravel 8
Php 8
Composer 2

**Comment by ckhandla94** [comment]
> > > Same here, any suggestions ?
> > 
> > 
> > I have just tried in latest version of backpack and larval, I have no error. If possible please describe error or send me screen shorts and versions of Backpack and Laravel
> 
> ![image](https://user-images.githubusercontent.com/8059351/146371487-8443fa06-a02b-418f-9c21-753895d43d5c.png) ![image](https://user-images.githubusercontent.com/8059351/146371553-558553f2-bafb-4df8-b9b5-58332d04698e.png)
> 
> Laravel 8 Php 8 Composer 2

It's strange, I think you don't need to run this command you can run `php artisan migrate` command

**Comment by WRedMedia** [comment]
Yep, no need )
Work fine without publish provider )
Thanks
